displayName=Player Stack Collapse
author=novot
description=Collapses right-click menus for multiple players into sub-menus.
tags=menu, player, stack, submenu, clutter
plugins=com.playerstackcollapse.PlayerStackCollapsePlugin